import {app} from '@azure/functions';import jwt from 'jsonwebtoken';import crypto from 'node:crypto';
const secret=()=>{if(!process.env.APPROVAL_SIGNING_SECRET)throw new Error('APPROVAL_SIGNING_SECRET missing');return process.env.APPROVAL_SIGNING_SECRET};
const json=(body,status=200)=>({status,jsonBody:body,headers:{'Cache-Control':'no-store'}});const body=async r=>await r.json();
const providers={
 'uber-eats':{auth:'oauth2',available:()=>!!process.env.UBER_CLIENT_ID},
 'doordash':{auth:'jwt',available:()=>!!process.env.DOORDASH_DEVELOPER_ID},
 'grubhub':{auth:'partner',available:()=>!!process.env.GRUBHUB_CLIENT_ID}
};
app.http('connect-start',{methods:['POST'],route:'connect/start',authLevel:'anonymous',handler:async(req)=>{let b=await body(req),p=providers[b.provider];if(!p)return json({error:'Unsupported provider'},400);if(!p.available())return json({error:`${b.provider} credentials are not configured`},503);return json({provider:b.provider,instructions:'Merchant/partner authorization must complete on the provider-hosted consent page. Secrets and refresh tokens remain server-side.'})}});
async function routeMatrix(origin,destinations){let key=process.env.GOOGLE_MAPS_API_KEY;if(!key)throw new Error('GOOGLE_MAPS_API_KEY missing');let payload={origins:[{waypoint:{address:origin}}],destinations:destinations.map(address=>({waypoint:{address}})),travelMode:'DRIVE',routingPreference:'TRAFFIC_AWARE'};let r=await fetch('https://routes.googleapis.com/distanceMatrix/v2:computeRouteMatrix',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key,'X-Goog-FieldMask':'originIndex,destinationIndex,duration,distanceMeters,status'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(`Routes API ${r.status}`);return await r.json()}
app.http('restaurants-search',{methods:['POST'],route:'restaurants/search',authLevel:'anonymous',handler:async(req)=>{let b=await body(req);if(!b.address||!b.query)return json({error:'Address and query required'},400);/* Provider catalog search belongs here after partner approval. */let catalog=[];if(!catalog.length)return json({restaurants:[],notice:'No approved provider catalog credential is configured. Add provider-specific search implementation after partner onboarding.'});let matrix=await routeMatrix(b.address,catalog.map(x=>x.address));return json({restaurants:catalog.map((x,i)=>({...x,distanceText:`${(matrix[i].distanceMeters/1609.344).toFixed(1)} mi`,durationText:matrix[i].duration}))})}});
app.http('orders-quote',{methods:['POST'],route:'orders/quote',authLevel:'anonymous',handler:async(req)=>{let b=await body(req);if(!providers[b.provider]?.available())return json({error:'Provider not connected'},403);/* Replace with provider quote/cart endpoint enabled for your approved account. */return json({error:'Live consumer checkout is unavailable until the named provider grants the required partner ordering scope.'},501)}});
app.http('orders-approval',{methods:['POST'],route:'orders/approval',authLevel:'anonymous',handler:async(req)=>{let b=await body(req);let quote=globalThis.quotes?.get?.(b.quoteId);if(!quote)return json({error:'Quote missing or expired'},404);let nonce=crypto.randomUUID(),exp=Math.floor(Date.now()/1000)+300;let token=jwt.sign({typ:'food_order_approval',quoteId:b.quoteId,total:quote.total,currency:quote.currency,nonce},secret(),{expiresIn:300,issuer:'amx-food-connector',audience:'amx-food-submit'});return json({approvalToken:token,summary:`Approve ${quote.totalFormatted} at ${quote.merchantName}`,expiresAt:new Date(exp*1000).toISOString()})}});
app.http('orders-submit',{methods:['POST'],route:'orders/submit',authLevel:'anonymous',handler:async(req)=>{let b=await body(req),claims;try{claims=jwt.verify(b.approvalToken,secret(),{issuer:'amx-food-connector',audience:'amx-food-submit'})}catch{return json({error:'Approval invalid or expired'},403)}if(claims.typ!=='food_order_approval')return json({error:'Wrong approval type'},403);/* Atomically consume nonce in durable storage, revalidate quote total/address, then call approved provider checkout. */return json({error:'Submission blocked until durable nonce storage and an approved provider checkout API are configured.'},503)}});